In [1]:
import sys
sys.path.append('../')
from plotting import CandlePlot
import pandas as pd
from technicals.indicators import BollingerBands, KeltnerChannels
from technicals.indicators import ATR, RSI, MACD

In [12]:
import plotly.graph_objects as go

In [2]:
df = pd.read_pickle("../data/USD_CAD_M5.pkl")

In [3]:
df_an = df.copy()

In [ ]:
df_an = MACD(df)

In [5]:
df_rs = RSI(df)

In [6]:
df_rs.tail()

,volume,time,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c,MACD,SIGNAL,HIST,RSI_14
138,280,2016-12-22 23:00:00+00:00,1.34876,1.34933,1.34876,1.34886,1.34841,1.34888,1.34841,1.34871,1.34912,1.34978,1.34902,1.34902,0.000439,-0.001911,0.002350,100.0
139,175,2016-12-27 03:00:00+00:00,1.35322,1.35352,1.35316,1.35351,1.35307,1.35339,1.35301,1.35337,1.35336,1.35367,1.35330,1.35365,0.001875,-0.001154,0.003029,100.0
140,66,2016-12-28 04:00:00+00:00,1.35732,1.35742,1.35728,1.35736,1.35721,1.35732,1.35715,1.35728,1.35743,1.35755,1.35739,1.35745,0.003286,-0.000266,0.003552,100.0
141,70,2016-12-29 05:00:00+00:00,1.35262,1.35277,1.35262,1.35269,1.35251,1.35269,1.35251,1.35258,1.35273,1.35286,1.35273,1.35280,0.003982,0.000584,0.003398,0.0
142,70,2016-12-30 06:00:00+00:00,1.34778,1.34782,1.34755,1.34758,1.34766,1.34769,1.34741,1.34746,1.34791,1.34794,1.34768,1.34771,0.004074,0.001282,0.002792,0.0

In [7]:
df_an.tail()

,volume,time,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c,MACD,SIGNAL,HIST,RSI_14
138,280,2016-12-22 23:00:00+00:00,1.34876,1.34933,1.34876,1.34886,1.34841,1.34888,1.34841,1.34871,1.34912,1.34978,1.34902,1.34902,0.000439,-0.001911,0.002350,100.0
139,175,2016-12-27 03:00:00+00:00,1.35322,1.35352,1.35316,1.35351,1.35307,1.35339,1.35301,1.35337,1.35336,1.35367,1.35330,1.35365,0.001875,-0.001154,0.003029,100.0
140,66,2016-12-28 04:00:00+00:00,1.35732,1.35742,1.35728,1.35736,1.35721,1.35732,1.35715,1.35728,1.35743,1.35755,1.35739,1.35745,0.003286,-0.000266,0.003552,100.0
141,70,2016-12-29 05:00:00+00:00,1.35262,1.35277,1.35262,1.35269,1.35251,1.35269,1.35251,1.35258,1.35273,1.35286,1.35273,1.35280,0.003982,0.000584,0.003398,0.0
142,70,2016-12-30 06:00:00+00:00,1.34778,1.34782,1.34755,1.34758,1.34766,1.34769,1.34741,1.34746,1.34791,1.34794,1.34768,1.34771,0.004074,0.001282,0.002792,0.0

In [14]:
df_plot = df_an.iloc[-300:]
cp = CandlePlot(df_plot, candles=True)
cp.show_plot(line_traces=[], sec_traces=[])

In [15]:
cp = CandlePlot(df_plot, candles=False)
cp.fig.add_trace(go.Bar(
    x=cp.df_plot.sTime,
    y=cp.df_plot.HIST,
    name="HIST"
))
cp.show_plot(line_traces=['SIGNAL', 'MACD'], sec_traces=[])